language: elixir

elixir: 1.6.5

otp_release: 20.3

matrix:
  include:
    - elixir: 1.6.5
      otp_release: 20.3
    - elixir: 1.6.4
      otp_release: 20.3
    - elixir: 1.6.0
      otp_release: 20.1

script:
  - mix test
  - MIX_ENV=test mix credo --format=oneline
